import type { Item } from "../context/BuilderContext";

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

export function exportBuildPdf(
  items: Item[],
  total: number
) {
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  iframe.setAttribute("aria-hidden", "true");
  document.body.appendChild(iframe);

  const printWindow = iframe.contentWindow;
  const printDocument = iframe.contentDocument;

  if (!printWindow || !printDocument) {
    iframe.remove();
    return false;
  }

  const rows =
    items.length > 0
      ? items
          .map(
            (item) => `
              <tr>
                <td>${escapeHtml(item.category)}</td>
                <td>${escapeHtml(item.name)}</td>
                <td class="price">$${item.price}</td>
              </tr>
            `
          )
          .join("")
      : `
          <tr>
            <td colspan="3" class="empty">No components selected</td>
          </tr>
        `;

  printDocument.open();
  printDocument.write(`
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Smart Bundle Builder Summary</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #0f172a;
          }
          .header {
            margin-bottom: 24px;
          }
          .title {
            font-size: 28px;
            font-weight: 700;
            margin: 0 0 8px;
          }
          .subtitle {
            color: #475569;
            font-size: 14px;
            margin: 0;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 24px;
          }
          th,
          td {
            border-bottom: 1px solid #e2e8f0;
            padding: 12px 0;
            text-align: left;
            font-size: 14px;
          }
          th {
            color: #475569;
            font-weight: 600;
          }
          .price {
            text-align: right;
            font-weight: 600;
          }
          .empty {
            color: #64748b;
            text-align: center;
            padding: 24px 0;
          }
          .total {
            display: flex;
            justify-content: space-between;
            font-size: 18px;
            font-weight: 700;
            border-top: 2px solid #cbd5e1;
            padding-top: 16px;
          }
          @media print {
            body {
              margin: 24px;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 class="title">Build Summary</h1>
          <p class="subtitle">Generated by Smart Bundle Builder</p>
        </div>

        <table>
          <thead>
            <tr>
              <th>Category</th>
              <th>Component</th>
              <th class="price">Price</th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
        </table>

        <div class="total">
          <span>Total</span>
          <span>$${total}</span>
        </div>
      </body>
    </html>
  `);

  printDocument.close();

  const cleanup = () => {
    window.setTimeout(() => {
      iframe.remove();
    }, 300);
  };

  printWindow.onafterprint = cleanup;
  printWindow.focus();
  window.setTimeout(() => {
    printWindow.print();
    cleanup();
  }, 150);

  return true;
}
